<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <RootNamespace>CandyUtilities</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>10</LangVersion>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>
    
    <ItemGroup>
        <Reference Include="UnityEngine" HintPath="$(EXILED_REFERENCES)\UnityEngine.dll" />
        <Reference Include="UnityEngine.CoreModule" HintPath="$(EXILED_REFERENCES)\UnityEngine.CoreModule.dll" />
        <Reference Include="Mirror" HintPath="$(EXILED_REFERENCES)\Mirror.dll" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="ExMod.Exiled" Version="9.6.0-beta7" />
    </ItemGroup>

</Project>
